// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zvNscEp5BXEtxDfGL1apV17WL22K5pk',
    appId: '1:974602888231:web:50488a80598fef592dda02',
    messagingSenderId: '974602888231',
    projectId: 'authentication-demo-d17b6',
    authDomain: 'authentication-demo-d17b6.firebaseapp.com',
    storageBucket: 'authentication-demo-d17b6.appspot.com',
    measurementId: 'G-965SZB0YF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3kOq8spsA5zhGuK-HKLTsfpWzaorxRp8',
    appId: '1:974602888231:android:076e6ce72f73a9c62dda02',
    messagingSenderId: '974602888231',
    projectId: 'authentication-demo-d17b6',
    storageBucket: 'authentication-demo-d17b6.appspot.com',
  );
}
